[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/duoan/TorchCode/blob/master/templates/02_softmax.ipynb)

# 🟢 Easy: Implement Softmax

Implement the **Softmax** function from scratch.

$$\text{softmax}(x_i) = \frac{e^{x_i}}{\sum_j e^{x_j}}$$

### Signature
```python
def my_softmax(x: torch.Tensor, dim: int = -1) -> torch.Tensor:
    ...
```

### Rules
- Do **NOT** use `torch.softmax`, `F.softmax`, or `torch.nn.Softmax`
- Must be **numerically stable** (hint: subtract `max` before `exp`)

### Example
```
Input:  tensor([1., 2., 3.])
Output: tensor([0.0900, 0.2447, 0.6652])  # sums to 1.0
```

### 補足：`x - x.max()` (数値安定性)
`x`に大きな数値(例えば1000)があると、`torch.exp(1000)`が`inf`に発散してしまう。最大値を引けば最大要素が0になるので`exp`の出力の上限が1に抑えられ、オーバーフローを抑えることが出来る。分子と分母に定数倍がかかるだけなので、数学的には等価となる。softmax()を書く時の定石。

In [ ]:
# Install torch-judge in Colab (no-op in JupyterLab/Docker)
try:
    import google.colab
    get_ipython().run_line_magic('pip', 'install -q torch-judge')
except ImportError:
    pass


In [4]:
import torch

/usr/local/lib/python3.11/site-packages/torch/_subclasses/functional_tensor.py:307: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:84.)
  cpu = _conversion_method_template(device=torch.device("cpu"))


In [5]:
# ✏️ YOUR IMPLEMENTATION HERE

def my_softmax(x: torch.Tensor, dim: int = -1) -> torch.Tensor:
    x_shifted = x - x.max(dim=dim, keepdim=True).values
    e_x = torch.exp(x_shifted)
    return e_x / e_x.sum(dim=dim, keepdim=True)

In [6]:
# 🧪 Debug
x = torch.tensor([1.0, 2.0, 3.0])
print(torch.exp(x.max()))
print(x.sum())
print("Output:", my_softmax(x, dim=-1))
print("Sum:   ", my_softmax(x, dim=-1).sum())  # should be ~1.0
print("Ref:   ", torch.softmax(x, dim=-1))

tensor(20.0855)
tensor(6.)
Output: tensor([0.0900, 0.2447, 0.6652])
Sum:    tensor(1.)
Ref:    tensor([0.0900, 0.2447, 0.6652])


In [38]:
# ✅ SUBMIT
from torch_judge import check
check("softmax")


🧪 Testing: Implement Softmax (Easy)
──────────────────────────────────────────────────
  ✅ [1/3] Basic 1-D (0.3ms)
  ✅ [2/3] 2-D along dim=-1 (0.4ms)
  ✅ [3/3] Numerical stability (0.2ms)
──────────────────────────────────────────────────
  🎉 All 3 tests passed! (0.9ms total)
  Progress saved. Run status() to see your dashboard.



In [7]:
tmp = torch.tensor([[1., 2., 3.],
                    [4., 5., 6.]]) # shape [2, 3]

print(tmp.sum()) # tensor(21def my_softmax(x: torch.Tensor, dim: int = -1) -> torch.Tensor:

tensor(21.)


- `dim`の指定で「どの方向につぶすか」が決まる

In [11]:
print(tmp.sum(dim=0))  # tensor(5., 7., 9.) → 「行」方向につぶす
print(tmp.sum(dim=1))  # tensor(6., 15.) → 「列」方向につぶす
print(tmp.sum(dim=-1)) # tensor(6., 15.) # 最後の次元について縮約する

tensor([5., 7., 9.])
tensor([ 6., 15.])
tensor([ 6., 15.])


- `keepdim=True`で次元を残せる

In [18]:
print("Tensor of False:", tmp.sum(dim=1, keepdim=False))
print("Tensor of True:", tmp.sum(dim=1, keepdim=True))

print("Shape of False:", tmp.sum(dim=1, keepdim=False).shape)
print("Shape of True:", tmp.sum(dim=1, keepdim=True).shape)

Tensor of False: tensor([ 6., 15.])
Tensor of True: tensor([[ 6.],
        [15.]])
Shape of False: torch.Size([2])
Shape of True: torch.Size([2, 1])
